language: node_js
node_js:
  - "6"

script:
  - npm run lint
  - npm run build

deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: "efektywnyaltruizm.org"
    acl: public_read
    region: eu-central-1
    upload-dir: $TRAVIS_BRANCH
    skip_cleanup: true
    local_dir: dist
    on:
      all_branches: true
      branches:
        except:
          - master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branches:
        only:
        - master
